version: "3.2"

services:
  rng:
    build: dockercoins/rng
    image: ${USERNAME}/rng:${TAG-latest}
    deploy:
      mode: global

  hasher:
    build: dockercoins/hasher
    image: ${USERNAME}/hasher:${TAG-latest}

  webui:
    build: dockercoins/webui
    image: ${USERNAME}/webui:${TAG-latest}
    #ports: #see dockercoins.override.yml

  redis:
    image: redis:alpine

  worker:
    build: dockercoins/worker
    image: ${USERNAME}/worker:${TAG-latest}
    deploy:
      replicas: 4

